export const LOAD_FEATURED_PROJECTS_DATA_SUCCESS = 'LOAD_FEATURED_PROJECTS_DATA_SUCCESS';
export const LOAD_PROJECTS_DATA_SUCCESS = 'LOAD_PROJECTS_DATA_SUCCESS';
export const LOAD_PROJECTS_PAGE_DATA_SUCCESS = 'LOAD_PROJECTS_PAGE_DATA_SUCCESS';
